### ISSUE TITLE
New Components and/or Features Suggestions.

### ISSUE THREAD

**Issue by TraderStf** [titon/toolkit#129]
Few suggestions to avoid reinventing the wheel, it is Toolkit, we need plenty of tools, plug-and-play 🎁

May be some are existing already in a way or another (perhaps needs a more 'obvious' example), I make this without checking the demo site.

Thank you for your time, keep up the good work!

<h3>Database</h3>
Very simple abstract layer: Create, Destroy, New, Add, Insert, Delete, Sort, Merge, Import, Export.
MySQL, SQLite, noSQL.

<h3>Sliders</h3>
![sliders](https://cloud.githubusercontent.com/assets/5954335/7064945/2b08d34e-deb3-11e4-8c48-984b720fa1d5.png)

<h3>Menus</h3>
In the demo, there is no showcase for Menu component, or is it Flyout and/or Drop, if it is the case, add an alias to it and a demo for usual classical menu types: with icons, subs, checkmarks...

<h3>Tab with Icons</h3>

<h3>Highlight Programming Code</h3>
http://alexgorbatchev.com/SyntaxHighlighter/

<h3>Parallax Scroll/Canvas</h3>

<h3>Cards</h3>
Cards for Shopping, Members, Team Presentation, Products...
Some type with zoom or pop-out window/dialog for more information and/or bigger photo, 3D models, color switching...

<h3>Chart/Graphical/Media Canvas</h3>
For math, stats, dashboard, city map, movies...

<h3>Miscellaneous</h3>
Date Picker, Calendar, Directory (Mac Finder / MS Explorer).

**Comment by milesj** [comment]
Thanks for these, definitely something to consider after 3.0 is complete.

As for the database suggestion, that seems like a more backend oriented piece, which would be covered by the Titon Framework: https://github.com/titon/framework and https://github.com/titon/db

**Comment by TraderStf** [comment]
Few more I think useful or 'trendy'.

<b>HybridAuth</b> - social logins in PHP.
http://hybridauth.sourceforge.net

<b>Mesh</b> is a universal interface for communicating with data sources whether it's your API, mongobus, pubnub, webrtc, socket.io, redis, or local storage. Easily build sophisticated features such as offline-mode, realtime data, rollbacks, and more with little effort.
https://github.com/mojo-js/mesh.js

**Comment by TraderStf** [comment]
Some might-be usefull tools.

<b>xto6</b> - JavaScript library to turn your janky old code into shiny new ES6 code.
https://github.com/mohebifar/xto6

**Comment by Strolen** [comment]
Just wanted to chime in really quick. 

First, loved the Toolkit as soon as I saw the size and feature support list. I am a Bootstrap refugee. It is now over used and while they have done a lot to become more efficient, it is still big...and overused.

This frontend is exactly what I was looking for.

From the list above, the only things I would be for adding would be a solid menu foundation like headroom.js which is popular and useful (then again, easy enough for anybody to incorporate) and perhaps a hero or card section just to round out the offerings. 

Otherwise, I think you already have most of the must have features and would, personally, prefer you master the core as you are.

My only request would be to provide some code snippets (example code for the example) in the demos. Having two different pages with the demo and component descriptions being divorced makes it somewhat of a chore to learn the pieces.

Just wanted to say I love it and am having a blast developing with it. Very clean and simple and easy to put together!! Thank you!

**Comment by milesj** [comment]
@Strolen Thanks for all the kind feedback! It's exactly what I'm trying to achieve with Toolkit.

As for the demos/examples. It's something I've also been working on, but haven't had the time to actually get up on the official website yet. Most of the work can be found in the demos folder here: https://github.com/titon/toolkit/tree/master/demo/components

**Comment by TraderStf** [comment]
I agree, great toolkit by cool guy... or the contrary? :+1:

**Comment by milesj** [comment]
Why not both? :P

**Comment by TraderStf** [comment]
Common not even in ASM to produce 3D GUI by AI :-p

**Comment by milesj** [comment]
A few more to add: 

Components - combobox, multi-combobox, datatable, toolbar, tree
Behaviors - form validation, drag and drop

**Comment by milesj** [comment]
More styles for breadcrumbs: http://codyhouse.co/demo/breadcrumbs-multi-steps-indicator/index.html

**Comment by shihabmalayil** [comment]
Important one is scrollspy.

**Comment by milesj** [comment]
@shihabmalayil That's what stalker does. http://titon.io/en/toolkit/2.1.6/components/stalker

**Comment by shihabmalayil** [comment]
@milesj Thanks

**Comment by milesj** [comment]
Closing this in favor of a new ticket: https://github.com/titon/toolkit/issues/164
